-- SQLite

SELECT NAME,COUNT(*) AS LOCATIONS, PHONENUMBER, CONTRACT_DATE, DESCRIPTION 
FROM EMPLOYEES e
JOIN POSITIONS p ON e.POSITION_ID = p.id
JOIN LOCATIONS l ON e.id = l.EMPLOYEE_ID
GROUP BY e.NAME
HAVING LOCATIONS >= 2;