-- SQLite

SELECT NAME, LASTNAME,COUNT(*) AS LOCATIONS, PHONE, EMAIL, ADDRESS, CITY, STATE, BIRTH_DATE 
FROM CUSTOMERS c
JOIN LOCATIONS l ON c.id = l.CUSTOMER_ID
GROUP BY c.NAME
HAVING LOCATIONS >= 2;